#!/usr/bin/env python3
"""
generate_domain_map.py — Per-agent domain import graph generator.

Runs after every commit (PostCommit hook) to keep domain maps current.
Generates DOMAIN_MAP.md for each agent's domain — a lightweight import graph
agents can query instead of reading multiple files to trace structure.

Domains mapped:
  Rex   → backend/app/      → backend/DOMAIN_MAP.md
  Aria  → frontend/src/     → frontend/DOMAIN_MAP.md

Output is a markdown file listing:
  - All Python/TypeScript modules in the domain
  - Their imports (within-domain only — no external packages)
  - Key hubs (files imported by 3+ other files)
  - Entry points (files that import others but aren't imported themselves)

Agents use this to answer: "what imports what?" without reading files.
"""

import ast
import re
import subprocess
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.stderr.reconfigure(encoding="utf-8", errors="replace")


def git_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True
    )
    return Path(result.stdout.strip())


def get_python_imports(file_path: Path, domain_root: Path) -> list[str]:
    """Extract within-domain imports from a Python file."""
    try:
        tree = ast.parse(file_path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return []

    imports = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            # Only capture app-internal imports (from app.xxx import yyy)
            if node.module.startswith("app.") or node.module.startswith("."):
                imports.append(node.module)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith("app."):
                    imports.append(alias.name)
    return imports


def get_ts_imports(file_path: Path, domain_root: Path) -> list[str]:
    """Extract within-domain imports from a TypeScript/TSX file."""
    try:
        content = file_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return []

    # Match: import ... from './xxx' or '../xxx' (relative imports only — within domain)
    pattern = re.compile(r'from\s+[\'"](\.[^"\']+)[\'"]')
    imports = pattern.findall(content)
    return imports


def build_python_map(domain_root: Path) -> dict[str, list[str]]:
    """Build import map for Python domain."""
    graph = {}
    for py_file in domain_root.rglob("*.py"):
        if "__pycache__" in str(py_file):
            continue
        rel = str(py_file.relative_to(domain_root))
        imports = get_python_imports(py_file, domain_root)
        graph[rel] = imports
    return graph


def build_ts_map(domain_root: Path) -> dict[str, list[str]]:
    """Build import map for TypeScript domain."""
    graph = {}
    for ts_file in domain_root.rglob("*.ts"):
        rel = str(ts_file.relative_to(domain_root))
        graph[rel] = get_ts_imports(ts_file, domain_root)
    for tsx_file in domain_root.rglob("*.tsx"):
        rel = str(tsx_file.relative_to(domain_root))
        graph[rel] = get_ts_imports(tsx_file, domain_root)
    return graph


def find_hubs(graph: dict[str, list[str]], threshold: int = 3) -> list[tuple[str, int]]:
    """Files imported by threshold or more other files — key hubs."""
    import_counts: dict[str, int] = {}
    for imports in graph.values():
        for imp in imports:
            import_counts[imp] = import_counts.get(imp, 0) + 1
    hubs = [(f, c) for f, c in import_counts.items() if c >= threshold]
    return sorted(hubs, key=lambda x: -x[1])


def find_entry_points(graph: dict[str, list[str]]) -> list[str]:
    """Files that import others but are imported by nobody — likely entry points."""
    all_imported = set()
    for imports in graph.values():
        all_imported.update(imports)
    return [f for f in graph if f not in all_imported and graph[f]]


LAST_UPDATED_RE = re.compile(r"^> Last updated: .+$", re.MULTILINE)


def write_domain_map(output_path: Path, domain_name: str, graph: dict[str, list[str]]) -> bool:
    """Write the DOMAIN_MAP.md file."""
    hubs = find_hubs(graph)
    entries = find_entry_points(graph)

    lines = [
        f"# DOMAIN_MAP.md — {domain_name}",
        f"> Auto-generated by generate_domain_map.py after each commit.",
        f"> Use this to understand module structure without reading files.",
        f"> Last updated: {__import__('datetime').date.today()}",
        "",
        "---",
        "",
        "## Key Hubs (imported by 3+ modules)",
        "",
    ]

    if hubs:
        for hub, count in hubs:
            lines.append(f"- `{hub}` — imported by {count} modules")
    else:
        lines.append("- (none yet — domain is small)")

    lines += [
        "",
        "## Entry Points (import others, not imported themselves)",
        "",
    ]

    if entries:
        for entry in entries:
            lines.append(f"- `{entry}`")
    else:
        lines.append("- (none yet)")

    lines += [
        "",
        "## Full Import Graph",
        "",
        "| Module | Imports (within-domain) |",
        "|---|---|",
    ]

    for module, imports in sorted(graph.items()):
        if imports:
            imp_str = ", ".join(f"`{i}`" for i in imports[:5])
            if len(imports) > 5:
                imp_str += f" (+{len(imports) - 5} more)"
        else:
            imp_str = "—"
        lines.append(f"| `{module}` | {imp_str} |")

    content = "\n".join(lines) + "\n"
    if output_path.is_file():
        existing = output_path.read_text(encoding="utf-8")
        if LAST_UPDATED_RE.sub("> Last updated: <date>", existing) == LAST_UPDATED_RE.sub(
            "> Last updated: <date>", content
        ):
            print(
                f">> {output_path.relative_to(output_path.parent.parent)} unchanged "
                f"({len(graph)} modules mapped)"
            )
            return False

    output_path.write_text(content, encoding="utf-8")
    print(f">> {output_path.relative_to(output_path.parent.parent)} updated ({len(graph)} modules mapped)")
    return True


def main() -> int:
    root = git_root()

    # Only regenerate after a real protocol step advances (flag written by
    # post_commit_next_step.py). Absent flag means nothing changed; skip the scan.
    flag_path = root / ".context" / "runtime" / "last_protocol_commit.flag"
    if not flag_path.exists():
        return 0

    # Rex's domain: backend/app/
    backend_domain = root / "backend" / "app"
    if backend_domain.exists():
        graph = build_python_map(backend_domain)
        write_domain_map(root / "backend" / "DOMAIN_MAP.md", "Rex — backend/app/", graph)

    # Aria's domain: frontend/src/
    frontend_domain = root / "frontend" / "src"
    if frontend_domain.exists():
        graph = build_ts_map(frontend_domain)
        write_domain_map(root / "frontend" / "DOMAIN_MAP.md", "Aria — frontend/src/", graph)

    # Generation succeeded -- consume the flag. If anything above raised,
    # the flag is retained so the next post-commit run retries.
    flag_path.unlink()
    return 0


if __name__ == "__main__":
    sys.exit(main())
